[2022-10-01 17:39:07,640] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: data_cleaning_dag.data_cleaning manual__2022-10-01T17:39:03.754394+00:00 [queued]>
[2022-10-01 17:39:07,665] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: data_cleaning_dag.data_cleaning manual__2022-10-01T17:39:03.754394+00:00 [queued]>
[2022-10-01 17:39:07,666] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-01 17:39:07,667] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-10-01 17:39:07,669] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-01 17:39:07,710] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): data_cleaning> on 2022-10-01 17:39:03.754394+00:00
[2022-10-01 17:39:07,724] {standard_task_runner.py:52} INFO - Started process 411 to run task
[2022-10-01 17:39:07,731] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_cleaning_dag', 'data_cleaning', 'manual__2022-10-01T17:39:03.754394+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/data_cleaning_dag/data_cleaning.py', '--cfg-path', '/tmp/tmp8gmio2ns', '--error-file', '/tmp/tmpp6e2w_gu']
[2022-10-01 17:39:07,736] {standard_task_runner.py:80} INFO - Job 5: Subtask data_cleaning
[2022-10-01 17:39:07,968] {task_command.py:371} INFO - Running <TaskInstance: data_cleaning_dag.data_cleaning manual__2022-10-01T17:39:03.754394+00:00 [running]> on host 408deac6c455
[2022-10-01 17:39:08,123] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_cleaning_dag
AIRFLOW_CTX_TASK_ID=data_cleaning
AIRFLOW_CTX_EXECUTION_DATE=2022-10-01T17:39:03.754394+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-01T17:39:03.754394+00:00
[2022-10-01 17:39:08,144] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_cleaning_dag/data_cleaning.py", line 15, in data_cleaning
    hotel_data = pd.read_csv("raw_data/hotel_bookings.csv") # Importing our raw data.
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'raw_data/hotel_bookings.csv'
[2022-10-01 17:39:08,175] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=data_cleaning_dag, task_id=data_cleaning, execution_date=20221001T173903, start_date=20221001T173907, end_date=20221001T173908
[2022-10-01 17:39:08,207] {standard_task_runner.py:97} ERROR - Failed to execute job 5 for task data_cleaning ([Errno 2] No such file or directory: 'raw_data/hotel_bookings.csv'; 411)
[2022-10-01 17:39:08,268] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-01 17:39:08,353] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
